blank_issues_enabled: false
contact_links:
  - name: Questions? Ask on X
    url: https://x.com/adxxya30
    about: For general questions about Coolema
    
issue_templates:
  - name: Add New Color Schema
    description: Propose a new terminal color schema
    template: schema-contribution.md
    labels:
      - add-schema
    assignees:
      - AdityaZxxx
